# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from gym_grpc import gym_pb2 as gym__grpc_dot_gym__pb2


class EnvStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Initialize = channel.unary_unary(
                '/env.Env/Initialize',
                request_serializer=gym__grpc_dot_gym__pb2.EnvID.SerializeToString,
                response_deserializer=gym__grpc_dot_gym__pb2.Status.FromString,
                )
        self.Reset = channel.unary_unary(
                '/env.Env/Reset',
                request_serializer=gym__grpc_dot_gym__pb2.ResetArgs.SerializeToString,
                response_deserializer=gym__grpc_dot_gym__pb2.ResetReturn.FromString,
                )
        self.Step = channel.unary_unary(
                '/env.Env/Step',
                request_serializer=gym__grpc_dot_gym__pb2.Action.SerializeToString,
                response_deserializer=gym__grpc_dot_gym__pb2.StepReturn.FromString,
                )


class EnvServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EnvServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=gym__grpc_dot_gym__pb2.EnvID.FromString,
                    response_serializer=gym__grpc_dot_gym__pb2.Status.SerializeToString,
            ),
            'Reset': grpc.unary_unary_rpc_method_handler(
                    servicer.Reset,
                    request_deserializer=gym__grpc_dot_gym__pb2.ResetArgs.FromString,
                    response_serializer=gym__grpc_dot_gym__pb2.ResetReturn.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=gym__grpc_dot_gym__pb2.Action.FromString,
                    response_serializer=gym__grpc_dot_gym__pb2.StepReturn.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'env.Env', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Env(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/env.Env/Initialize',
            gym__grpc_dot_gym__pb2.EnvID.SerializeToString,
            gym__grpc_dot_gym__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/env.Env/Reset',
            gym__grpc_dot_gym__pb2.ResetArgs.SerializeToString,
            gym__grpc_dot_gym__pb2.ResetReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/env.Env/Step',
            gym__grpc_dot_gym__pb2.Action.SerializeToString,
            gym__grpc_dot_gym__pb2.StepReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
